version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-express
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud-server
    ports:
      - "9000:9000"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=crud
      - PORT=9000
    depends_on:
      - mongodb

volumes:
  mongodb_data:
