apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: monitoring
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  type: NodePort
  ports:
  - name: web
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: {{ .Values.service.nodePort }}
