replicaCount: 1

image:
  repository: nthhaf/hant-api-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 80
  nodePort: 30002

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
