replicaCount: 1

image:
  repository: nthhaf/hant-api-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  nodePort: 30002

mongo:
  MONO_URI: "mongodb+srv://hant:kgA5BbqfQCoJDmR4@cluster73289.pchihpf.mongodb.net/vdt2024?retryWrites=true&w=majority&appName=Cluster73289"
