name: Build and Publish docker image
run-name: "Publish docker image commit sha ${{ inputs.SHA || github.sha }} by @${{ github.actor }}"

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: self-hosted
    outputs: 
      tag: ${{ steps.get_tag.outputs.mytag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/hant-api-service
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,event=tag,pattern={{raw}}
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Get tag
        id: get_tag
        run: |
          echo "mytag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT  

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/backend-cache:latest
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/backend-cache:latest,mode=max

  modify_image_tag:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout config repository
        uses: actions/checkout@v3
        with:
          repository: hantbk/api_config
          token: ${{ secrets.MY_REPO_TOKEN }}
          ref: main

      - name: Modify image tag in values.yaml
        run: |
          TAG=${{ needs.build.outputs.tag }}
          echo "Updating image tag to $TAG"
          sed -i.bak "s/tag: .*/tag: \"$TAG\"/" values.yaml
          cat values.yaml  # Print values.yaml for debugging

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.MY_REPO_TOKEN }}
        run: |
          git config --global user.email 'captainnemot1k60@gmail.com'
          git config --global user.name 'hantbk'
          rm values.yaml.bak
          git add values.yaml
          git commit -m "Update image tag by GitHub Actions Job change manifest: ${{ github.run_number }}"
          git push origin main
